# Generated by Django 5.1.5 on 2025-12-09 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_usuarios', models.IntegerField()),
                ('limite_produtos', models.IntegerField(blank=True, null=True)),
                ('inclui_pdv', models.BooleanField(default=True)),
                ('inclui_estoque', models.BooleanField(default=True)),
                ('inclui_financeiro', models.BooleanField(default=False)),
                ('inclui_relatorios', models.BooleanField(default=False)),
                ('inclui_backup', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de Licença',
                'verbose_name_plural': 'Planos de Licença',
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chave_licenca', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenca', to='core.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenca.planolicenca')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
            },
        ),
        migrations.CreateModel(
            name='HistoricoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('data_anterior', models.DateField(blank=True, null=True)),
                ('data_nova', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='licenca.licenca')),
            ],
            options={
                'verbose_name': 'Histórico de Licença',
                'verbose_name_plural': 'Histórico de Licenças',
            },
        ),
    ]
