# Generated by Django 6.0.2 on 2026-02-15 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_regime'),
        ('licenca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoBypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_faturado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Pago Parcialmente'), ('pago', 'Liquidado')], default='pendente', max_length=20)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
