# Generated by Django 5.1.5 on 2025-12-09 13:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_automatico', models.BooleanField(default=True, verbose_name='Ativar Backup Automático')),
                ('frequencia_backup', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal')], default='diario', max_length=15, verbose_name='Frequência')),
                ('horario_backup', models.TimeField(default='02:00', verbose_name='Horário do Backup')),
                ('dias_retencao_backup', models.IntegerField(default=30, help_text='Número de dias que os ficheiros de backup devem ser mantidos.', verbose_name='Reter Backups por (dias)')),
                ('notificar_erro', models.BooleanField(default=True, verbose_name='Notificar em Caso de Erro')),
                ('email_notificacao', models.EmailField(blank=True, help_text='Endereço de email para receber alertas de falha no backup.', max_length=254, verbose_name='Email para Notificações')),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
                ('status_ultimo_backup', models.CharField(blank=True, choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('em_andamento', 'Em Andamento')], max_length=20)),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configurações de Backup',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, help_text='Ex: Neway Farmácia', max_length=255)),
                ('nif', models.CharField(help_text='Número de Identificação Fiscal da empresa.', max_length=14, verbose_name='NIF')),
                ('email', models.CharField(blank=True, help_text='Ex: empresa@gmail.com', max_length=200)),
                ('site', models.CharField(blank=True, help_text='Ex: empresa.com', max_length=200)),
                ('telefone', models.CharField(blank=True, help_text='Ex: contacto da empresa', max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=4)),
                ('regime_tributario', models.CharField(choices=[('geral', 'Regime Geral'), ('simplificado', 'Regime Simplificado (IVA)'), ('exclusao', 'Regime de Não Sujeição (Exclusão)'), ('outros', 'Outros (Regimes especiais e outros)')], default='geral', max_length=20)),
                ('impressora_cupom', models.CharField(blank=True, help_text='Nome da impressora para talões e recibos (ex: POS-80).', max_length=200, verbose_name='Impressora de Talões')),
            ],
            options={
                'verbose_name': 'Configuração Fiscal',
                'verbose_name_plural': 'Configurações Fiscais',
            },
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_banco', models.CharField(max_length=150, verbose_name='Nome do Banco')),
                ('numero_conta', models.CharField(max_length=50, verbose_name='Número da Conta')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, null=True, verbose_name='SWIFT/BIC')),
            ],
            options={
                'verbose_name': 'Dado Bancário',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
        migrations.CreateModel(
            name='HistoricoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=15, verbose_name='Tipo de Backup')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='processando', max_length=15, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('ficheiro_backup', models.FileField(blank=True, null=True, upload_to='backups/%Y/%m/', verbose_name='Ficheiro do Backup')),
                ('tamanho_ficheiro', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('detalhes_erro', models.TextField(blank=True, verbose_name='Detalhes do Erro')),
            ],
            options={
                'verbose_name': 'Histórico de Backup',
                'verbose_name_plural': 'Históricos de Backup',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizacaoInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('auto', 'Automático (Sistema)')], default='auto', max_length=20)),
                ('cor_primaria', models.CharField(default='#5D5CDE', help_text='Cor principal da interface (hexadecimal, ex: #5D5CDE)', max_length=7)),
                ('logo_principal', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
            ],
            options={
                'verbose_name': 'Personalização de Interface',
                'verbose_name_plural': 'Personalizações de Interface',
            },
        ),
    ]
