# Generated by Django 5.1.5 on 2025-12-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguracao',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_backup', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='empresa',
            field=models.OneToOneField(help_text='Ex: Farmácia Neway LDA', on_delete=django.db.models.deletion.CASCADE, related_name='config_fiscal', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='configuracao_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='configuracoes.configuracaofiscal'),
        ),
        migrations.AddField(
            model_name='historicobackup',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_backups', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='historicobackup',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, help_text='Utilizador que iniciou o backup manual.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalizacaointerface',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='personalizacaointerface',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='personalizacaointerface',
            unique_together={('empresa', 'usuario')},
        ),
    ]
