# Generated by Django 6.0.2 on 2026-02-11 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoriaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('SISTEMA', 'Manutenção de Sistema'), ('TENANT_CRUD', 'Gestão de Empresas/Clientes'), ('LICENCA', 'Gestão de Licenciamento'), ('SEGURANCA', 'Segurança e Acessos Admin'), ('MIGRATION', 'Alterações de Base de Dados')], max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('AVISO', 'Aviso/Risco'), ('CRITICO', 'Erro Crítico/Invasão')], default='INFO', max_length=10)),
                ('acao', models.CharField(help_text="Ex: Criação de novo Tenant 'Farmácia Central'", max_length=255)),
                ('dados_contexto', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('empresa_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Log de Auditoria Pública',
                'verbose_name_plural': 'Logs de Auditoria Pública',
                'ordering': ['-created_at'],
            },
        ),
    ]
