# Generated by Django 6.0.2 on 2026-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='recebe_copia_faturamento_email',
            field=models.BooleanField(default=False, help_text='Se marcado, receberá um e-mail a cada documento fiscal emitido na empresa.', verbose_name='Receber Cópia de Faturamento?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='recebe_copia_faturamento_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Receber via WhatsApp?'),
        ),
    ]
