# Generated by Django 6.0.2 on 2026-02-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_recebe_copia_faturamento_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='recebe_copia_faturamento_email',
            field=models.BooleanField(default=False, help_text='Diretores e Gerentes recebem uma cópia de cada documento fiscal emitido.', verbose_name='Receber Cópia de Faturamento?'),
        ),
    ]
