# Generated by Django 6.0.2 on 2026-02-14 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0002_empresa_regime'),
        ('funcionarios', '0003_alter_funcionario_recebe_copia_faturamento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='categoria',
            field=models.CharField(choices=[('diretoria', 'Diretoria'), ('gerencia', 'Gerência'), ('coordenacao', 'Coordenação'), ('supervisao', 'Supervisão'), ('operacional', 'Operacional'), ('tecnico', 'Técnico'), ('administrativo', 'Administrativo'), ('vendas', 'Vendas'), ('direcao_tecnica', 'Direção Técnica'), ('estagiario', 'Estagiário'), ('rh', 'Recursos Humanos'), ('financeiro', 'Contabilidade'), ('outros', 'Outros')], default='operacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel_hierarquico',
            field=models.IntegerField(default=1, help_text='1 = Nível mais alto'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissões do Django'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='selecionar_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='empresas.loja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsavel', to='funcionarios.funcionario'),
        ),
    ]
