# Generated by Django 6.0.2 on 2026-02-11 22:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
            },
        ),
        migrations.CreateModel(
            name='ComprovativoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovativos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Comprovativo de Compra',
                'verbose_name_plural': 'Comprovativos de Compra',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('cv', models.FileField(upload_to='candidaturas/')),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('avaliada', 'Avaliadas'), ('rejeitada', 'Rejeitada'), ('aceita', 'Aceita')], default='pendente', max_length=50)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='site.concurso')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('conteudo_json', models.JSONField(default=dict)),
                ('nome_exibicao', models.CharField(default='Minha Empresa', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.AddField(
            model_name='concurso',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos', to='site.pagina'),
        ),
        migrations.CreateModel(
            name='ClienteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('pessoa_juridica', models.BooleanField(default=False)),
                ('registrado', models.BooleanField(default=False)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_site', to='site.pagina')),
            ],
            options={
                'verbose_name': 'Cliente Site',
                'verbose_name_plural': 'Clientes Site',
            },
        ),
        migrations.CreateModel(
            name='ProdutoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('permitir_entrega', models.BooleanField(default=True)),
                ('preco_customizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_site', to='site.pagina')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Produto no Site',
                'verbose_name_plural': 'Produtos no Site',
            },
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_nome', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefone', models.CharField(blank=True, max_length=50)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('documentos', models.FileField(blank=True, null=True, upload_to='reclamacoes/')),
                ('imagens', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagens')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvida', 'Resolvida')], default='pendente', max_length=50)),
                ('atendido', models.BooleanField(default=False)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to='site.pagina')),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('carrossel', 'Carrossel'), ('card', 'Card'), ('imagem_fixa', 'Imagem Fixa'), ('texto', 'Texto')], max_length=50)),
                ('dados', models.JSONField(default=dict)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='site.pagina')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('contato', 'Contato'), ('compra_produto', 'Compra de Produto'), ('compra_servico', 'Compra de Serviço')], default='contato', max_length=50)),
                ('atendido', models.BooleanField(default=False)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_contato', to='site.pagina')),
            ],
            options={
                'verbose_name': 'Solicitação de Contato',
                'verbose_name_plural': 'Solicitações de Contato',
            },
        ),
    ]
