# Generated by Django 6.0.2 on 2026-02-15 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='em_rascunho',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='preview_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
