# Generated by Django 5.1.5 on 2025-12-09 13:16

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('nif', models.CharField(max_length=10, unique=True)),
                ('codigo_validacao', models.CharField(blank=True, help_text='Código de validação fornecido pela AGT para ATCUD', max_length=500, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('provincia', models.CharField(choices=[('BGO', 'Bengo'), ('ICB', 'Icolo e Bengo'), ('BGU', 'Benguela'), ('BIE', 'Bié'), ('CAB', 'Cabinda'), ('CCS', 'Cuando Cubango'), ('CNO', 'Cuanza Norte'), ('CUS', 'Cuanza Sul'), ('CNN', 'Cunene'), ('HUA', 'Huambo'), ('HUI', 'Huíla'), ('LUA', 'Luanda'), ('LNO', 'Lunda Norte'), ('LSU', 'Lunda Sul'), ('MAL', 'Malanje'), ('MOX', 'Moxico'), ('NAM', 'Namibe'), ('UIG', 'Uíge'), ('ZAI', 'Zaire')], max_length=50)),
                ('postal', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('ativa', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=9)),
                ('provincia', models.CharField(choices=[('BGO', 'Bengo'), ('ICB', 'Icolo e Bengo'), ('BGU', 'Benguela'), ('BIE', 'Bié'), ('CAB', 'Cabinda'), ('CCS', 'Cuando Cubango'), ('CNO', 'Cuanza Norte'), ('CUS', 'Cuanza Sul'), ('CNN', 'Cunene'), ('HUA', 'Huambo'), ('HUI', 'Huíla'), ('LUA', 'Luanda'), ('LNO', 'Lunda Norte'), ('LSU', 'Lunda Sul'), ('MAL', 'Malanje'), ('MOX', 'Moxico'), ('NAM', 'Namibe'), ('UIG', 'Uíge'), ('ZAI', 'Zaire')], max_length=50)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativa', models.BooleanField(default=True)),
                ('eh_matriz', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('e_administrador_empresa', models.BooleanField(default=False, help_text='Se marcado, este utilizador pode gerir todas as lojas e utilizadores da sua empresa.', verbose_name='É Administrador da Empresa?')),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.loja')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FR', 'Fatura Recibo'), ('FT', 'Fatura'), ('REC', 'Recibo'), ('PP', 'Fatura Proforma'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('DT', 'Documento de Transporte'), ('VD', 'Venda a Dinheiro'), ('TV', 'Talão de Venda'), ('TD', 'Talão de Devolução'), ('AA', 'Alienação de Ativos'), ('DA', 'Devolução de Ativos'), ('RP', 'Prémio ou Penalização'), ('RE', 'Estorno ou Anulação'), ('CS', 'Imputação a Co-Produtos'), ('LD', 'Lançamentos Diversos'), ('RA', 'Resseguro Aceite'), ('RC', 'Resseguro Cedido')], max_length=5, unique=True, verbose_name='Tipo de Documento')),
                ('ano', models.IntegerField(default=2025)),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Contador de Documento',
                'verbose_name_plural': 'Contadores de Documentos',
                'unique_together': {('empresa', 'tipo_documento', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_categoria_empresa_nome')],
            },
        ),
    ]
