# Generated by Django 5.1.5 on 2025-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_codigo_validacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_validacao',
            field=models.CharField(blank=True, help_text='Código de validação fornecido pela AGT para ATCUD', max_length=500, null=True),
        ),
    ]
