# Generated by Django 6.0.2 on 2026-02-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('empresas', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0002_initial'),
        ('funcionarios', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoimposto',
            name='responsavel_fiscal',
            field=models.ForeignKey(blank=True, help_text='Funcionário responsável pelos assuntos fiscais', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='conciliacaobancaria',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_relacionada', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contapai',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_pagar', to='financeiro.contapai'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_relacionada', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_receber', to='financeiro.contapai'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='conta_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contareceber'),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_relacionada', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='conta_bancaria_pagamento',
            field=models.ForeignKey(blank=True, help_text='Conta utilizada para pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela apuração', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_relacionada', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='conta_destino',
            field=models.ForeignKey(blank=True, help_text='Para transferências entre contas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='recibo',
            field=models.ForeignKey(blank=True, help_text='Recibo de Pagamento (REC) que originou esta entrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financeiras_origem', to='vendas.recibo'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='usuario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='venda_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='impostotributo',
            name='movimentacao_pagamento',
            field=models.ForeignKey(blank=True, help_text='Movimentação de pagamento do imposto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_angola_pagos', to='financeiro.movimentacaofinanceira'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='conta_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contareceber'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.loja'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='movimento_original',
            field=models.ForeignKey(blank=True, help_text='Movimento original que está sendo estornado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financeiro.movimentocaixa'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo movimento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='venda_relacionada',
            field=models.ForeignKey(blank=True, help_text='Venda que originou este movimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriafinanceira',
            unique_together={('nome', 'empresa', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('codigo', 'empresa')},
        ),
        migrations.AddIndex(
            model_name='configuracaoimposto',
            index=models.Index(fields=['regime_tributario_principal'], name='financeiro__regime__e197b4_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaoimposto',
            index=models.Index(fields=['setor_atividade'], name='financeiro__setor_a_3e98ff_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaoimposto',
            index=models.Index(fields=['provincia'], name='financeiro__provinc_fe0abc_idx'),
        ),
        migrations.AddIndex(
            model_name='contapai',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_6a94aa_idx'),
        ),
        migrations.AddIndex(
            model_name='contapai',
            index=models.Index(fields=['status', 'empresa'], name='financeiro__status_6a052d_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_d25c79_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['fornecedor', 'status'], name='financeiro__fornece_77d83a_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['status', 'empresa'], name='financeiro__status_dc403b_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_cf81e6_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente', 'status'], name='financeiro__cliente_62fae2_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status', 'empresa'], name='financeiro__status_f04d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['data_movimentacao', 'empresa'], name='financeiro__data_mo_f66e75_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['conta_bancaria', 'confirmada'], name='financeiro__conta_b_1f9a61_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['status', 'data_vencimento'], name='financeiro__status_168a56_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['tipo_movimentacao', 'data_movimentacao'], name='financeiro__tipo_mo_b2a82e_idx'),
        ),
        migrations.AddIndex(
            model_name='impostotributo',
            index=models.Index(fields=['codigo_receita_agt', 'situacao'], name='financeiro__codigo__bf3f16_idx'),
        ),
        migrations.AddIndex(
            model_name='impostotributo',
            index=models.Index(fields=['data_vencimento', 'situacao'], name='financeiro__data_ve_835b51_idx'),
        ),
        migrations.AddIndex(
            model_name='impostotributo',
            index=models.Index(fields=['ano_referencia', 'mes_referencia'], name='financeiro__ano_ref_472f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='impostotributo',
            index=models.Index(fields=['regime_tributario', 'empresa'], name='financeiro__regime__f9372e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='impostotributo',
            unique_together={('empresa', 'codigo_receita_agt', 'ano_referencia', 'mes_referencia')},
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['data_movimento', 'loja'], name='financeiro__data_mo_a9d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['tipo_movimento', 'status'], name='financeiro__tipo_mo_9c9725_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['usuario', 'data_movimento'], name='financeiro__usuario_699dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['venda_relacionada'], name='financeiro__venda_r_d1da98_idx'),
        ),
    ]
