# Generated by Django 5.1.5 on 2025-12-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaestoque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.lote'),
        ),
        migrations.AddField(
            model_name='alertaestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_estoque', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='alertaestoque',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorias incluídas (vazio = todas)', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='core.loja'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsaveis_contagem',
            field=models.ManyToManyField(help_text='Usuários responsáveis pela contagem', related_name='inventarios_contagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsavel_planejamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_planejados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='usuario_contagem_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='usuario_contagem_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_loja', to='core.loja'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_produto', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['tipo_alerta', 'ativo'], name='estoque_ale_tipo_al_4ea9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['prioridade', 'ativo'], name='estoque_ale_priorid_a29c16_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['produto', 'loja'], name='estoque_ale_produto_e9a776_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='iteminventario',
            unique_together={('inventario', 'produto')},
        ),
    ]
