# Generated by Django 6.0.2 on 2026-08-10 22:10

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_lote', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('quantidade_inicial', models.IntegerField()),
                ('quantidade_atual', models.IntegerField()),
                ('preco_custo_lote', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='PrincipioAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Substância')),
                ('nome_cientifico', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_cas', models.CharField(blank=True, help_text='Identificador químico universal', max_length=20, null=True, verbose_name='Código CAS')),
                ('codigo_atc', models.CharField(blank=True, help_text='Classificação Anatômica Terapêutica Química', max_length=20, null=True, verbose_name='Código ATC')),
                ('classe_terapeutica', models.CharField(blank=True, max_length=255, null=True)),
                ('lista_controle', models.CharField(blank=True, help_text='Ex: Portaria 344 (se aplicável em Angola/região)', max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Princípio Ativo',
                'verbose_name_plural': 'Princípios Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='ControleVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dias_para_alerta', models.IntegerField(default=30)),
                ('alerta_gerado', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_vencimento', to='produtos.lote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertaProdutoExpiracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dias_alerta', models.IntegerField(default=30)),
                ('enviado', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_expiracao', to='produtos.lote')),
            ],
            options={
                'verbose_name': 'Alerta de Produto Prestes a Expirar',
                'verbose_name_plural': 'Alertas de Produtos Prestes a Expirar',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_interno', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('nome_produto', models.CharField(max_length=200)),
                ('nome_comercial', models.CharField(max_length=200)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='DESCONTO (%)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('estoque_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.categoria')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.fabricante')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
                ('principio_ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.principioativo', verbose_name='Princípio Ativo / Composição Base')),
                ('taxa_iva', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='fiscal.taxaivaagt', verbose_name='Taxa de IVA/Imposto Legal (AGT)')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'unique_together': {('codigo_interno',)},
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produtos.produto'),
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_custo_anterior', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_venda_anterior', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_custo_novo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_venda_novo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('motivo', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_precos_registrados', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('produto', 'numero_lote')},
        ),
        migrations.CreateModel(
            name='ComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concentracao', models.CharField(help_text='Ex: 500mg, 10mg/ml, 5%', max_length=50, verbose_name='Concentração/Dose')),
                ('is_principal', models.BooleanField(default=True, help_text='Marcar se este for o componente principal da fórmula.', verbose_name='Ativo Principal?')),
                ('principio_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vinculados', to='produtos.principioativo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Composição do Produto',
                'verbose_name_plural': 'Composições dos Produtos',
                'unique_together': {('produto', 'principio_ativo')},
            },
        ),
    ]
