# Generated by Django 6.0.2 on 2026-02-12 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipioAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Substância')),
                ('nome_cientifico', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_cas', models.CharField(blank=True, help_text='Identificador químico universal', max_length=20, null=True, verbose_name='Código CAS')),
                ('codigo_atc', models.CharField(blank=True, help_text='Classificação Anatômica Terapêutica Química', max_length=20, null=True, verbose_name='Código ATC')),
                ('classe_terapeutica', models.CharField(blank=True, max_length=255, null=True)),
                ('lista_controle', models.CharField(blank=True, help_text='Ex: Portaria 344 (se aplicável em Angola/região)', max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principios_ativos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Princípio Ativo',
                'verbose_name_plural': 'Princípios Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='principio_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.principioativo', verbose_name='Princípio Ativo / Composição Base'),
        ),
        migrations.CreateModel(
            name='ComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concentracao', models.CharField(help_text='Ex: 500mg, 10mg/ml, 5%', max_length=50, verbose_name='Concentração/Dose')),
                ('is_principal', models.BooleanField(default=True, help_text='Marcar se este for o componente principal da fórmula.', verbose_name='Ativo Principal?')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='produtos.produto')),
                ('principio_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vinculados', to='produtos.principioativo')),
            ],
            options={
                'verbose_name': 'Composição do Produto',
                'verbose_name_plural': 'Composições dos Produtos',
                'unique_together': {('produto', 'principio_ativo')},
            },
        ),
    ]
