# Generated by Django 6.0.2 on 2026-02-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscallinha',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='retencaofonte',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, help_text='Conta a pagar que gerou esta retenção', null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='retencaofonte',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='retencaofonte',
            name='fornecedor',
            field=models.ForeignKey(help_text='Fornecedor/Prestador de serviço a quem foi efetuada a retenção', on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='saftexport',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saft_exports', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='saftexport',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saft_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='saftexport',
            name='usuario_geracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saft_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por'),
        ),
        migrations.AddField(
            model_name='taxaivaagt',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_iva', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='documentofiscallinha',
            name='taxa_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Taxa de IVA'),
        ),
        migrations.AlterUniqueTogether(
            name='contadordocumento',
            unique_together={('empresa', 'tipo_documento', 'ano', 'serie')},
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['empresa', 'data_emissao'], name='fiscal_docu_empresa_2b4be2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['empresa', 'status'], name='fiscal_docu_empresa_10529b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['cliente', 'data_emissao'], name='fiscal_docu_cliente_8097de_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['numero_documento'], name='fiscal_docu_numero__7c24db_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['atcud'], name='fiscal_docu_atcud_f78591_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['hash_documento'], name='fiscal_docu_hash_do_062bea_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'serie', 'numero'), name='unique_documento_por_empresa_serie'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'atcud'), name='unique_atcud_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='saftexport',
            index=models.Index(fields=['empresa', 'periodo_tributacao'], name='fiscal_saft_empresa_f2adb8_idx'),
        ),
        migrations.AddIndex(
            model_name='saftexport',
            index=models.Index(fields=['status'], name='fiscal_saft_status_f0f751_idx'),
        ),
        migrations.AddIndex(
            model_name='saftexport',
            index=models.Index(fields=['hash_arquivo'], name='fiscal_saft_hash_ar_464d08_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscallinha',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_linha'), name='unique_linha_por_documento'),
        ),
    ]
