# Generated by Django 5.1.5 on 2025-11-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assinaturadigital',
            options={'verbose_name': 'Assinatura Fiscal', 'verbose_name_plural': 'Assinaturas Fiscais'},
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='chave_privada',
            field=models.TextField(blank=True, help_text='Chave privada RSA cifrada (Fernet). Mantenha em segredo', null=True),
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='chave_publica',
            field=models.TextField(blank=True, help_text='Chave pública RSA PEM.', null=True),
        ),
    ]
