# Generated by Django 5.1.5 on 2025-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturadigital',
            name='dados_series_fiscais',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados de Hash e Código AGT por Série'),
        ),
    ]
