# Generated by Django 6.0.2 on 2026-08-10 22:10

import cloudinary.models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('regime', models.CharField(choices=[('COMERCIO', 'Regime de Comércio'), ('SERVICOS', 'Regime de Prestação de Serviços'), ('MISTO', 'Regime Misto (Comércio e Serviços)')], default='MISTO', help_text='Define as regras de tributação e incidência de IVA da empresa.', max_length=20, verbose_name='Regime Fiscal')),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('nif', models.CharField(max_length=10, unique=True)),
                ('codigo_validacao', models.CharField(blank=True, help_text='Código de validação fornecido pela AGT para ATCUD', max_length=500, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('provincia', models.CharField(choices=[('BGO', 'Bengo'), ('ICB', 'Icolo e Bengo'), ('BGU', 'Benguela'), ('BIE', 'Bié'), ('CAB', 'Cabinda'), ('CCS', 'Cuando Cubango'), ('CNO', 'Cuanza Norte'), ('CUS', 'Cuanza Sul'), ('CNN', 'Cunene'), ('HUA', 'Huambo'), ('HUI', 'Huíla'), ('LUA', 'Luanda'), ('LNO', 'Lunda Norte'), ('LSU', 'Lunda Sul'), ('MAL', 'Malanje'), ('MOX', 'Moxico'), ('NAM', 'Namibe'), ('UIG', 'Uíge'), ('ZAI', 'Zaire')], max_length=50)),
                ('postal', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('ativa', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome',), name='unique_categoria_nome_por_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Domínio de Acesso',
                'verbose_name_plural': 'Domínios de Acesso',
            },
        ),
    ]
