# Generated by Django 6.0.2 on 2026-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regime',
            field=models.CharField(choices=[('COMERCIO', 'Regime de Comércio'), ('SERVICOS', 'Regime de Prestação de Serviços'), ('MISTO', 'Regime Misto (Comércio e Serviços)')], default='MISTO', help_text='Define as regras de tributação e incidência de IVA da empresa.', max_length=20, verbose_name='Regime Fiscal'),
        ),
    ]
