# Generated by Django 5.1.5 on 2025-12-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('comandas', '0002_initial'),
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centrorequisicao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_responsavel', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas_atendidas', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='configuracaocomanda',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_comandas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='historicocomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='historicocomanda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.mesa'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='item_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.itemcomanda'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='movimentacaocomanda',
            name='pagamento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.pagamento'),
        ),
        migrations.AddField(
            model_name='produtocomanda',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.categoriacomanda'),
        ),
        migrations.AddField(
            model_name='produtocomanda',
            name='centro_requisicao',
            field=models.ForeignKey(blank=True, help_text='Centro responsável pelo preparo deste item', null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.centrorequisicao'),
        ),
        migrations.AddField(
            model_name='produtocomanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='itemtemplatecomanda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandas.produtocomanda'),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.produtocomanda'),
        ),
        migrations.AddField(
            model_name='templatecomanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='itemtemplatecomanda',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_template', to='comandas.templatecomanda'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriacomanda',
            unique_together={('nome', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='centrorequisicao',
            unique_together={('codigo', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'loja')},
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['numero_comanda'], name='comandas_co_numero__c5502c_idx'),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['status', 'data_abertura'], name='comandas_co_status_eb44c5_idx'),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['atendente', 'data_abertura'], name='comandas_co_atenden_66e14d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocomanda',
            index=models.Index(fields=['comanda', 'data_movimentacao'], name='comandas_mo_comanda_34d380_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocomanda',
            index=models.Index(fields=['tipo_movimentacao', 'data_movimentacao'], name='comandas_mo_tipo_mo_c15bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='produtocomanda',
            index=models.Index(fields=['codigo'], name='comandas_pr_codigo_84ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='produtocomanda',
            index=models.Index(fields=['categoria', 'disponivel'], name='comandas_pr_categor_de5500_idx'),
        ),
    ]
