# Generated by Django 6.0.2 on 2026-02-11 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_operacao', models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Exclusão')], max_length=10)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_posteriores', models.JSONField(blank=True, null=True)),
                ('campos_alterados', models.JSONField(default=list)),
                ('motivo', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pode_auditar_vendas', models.BooleanField(default=False)),
                ('pode_auditar_estoque', models.BooleanField(default=False)),
                ('pode_auditar_financeiro', models.BooleanField(default=False)),
                ('pode_auditar_produtos', models.BooleanField(default=False)),
                ('pode_auditar_fiscal', models.BooleanField(default=False)),
                ('pode_auditar_tudo', models.BooleanField(default=False, help_text='Libera auditoria de todas as apps')),
            ],
            options={
                'verbose_name': 'Vínculo de Auditoria de Investimento',
                'verbose_name_plural': 'Vínculos de Auditoria de Investimento',
            },
        ),
        migrations.CreateModel(
            name='DashboardPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict)),
                ('widgets', models.JSONField(default=list)),
                ('filtros_padrao', models.JSONField(default=dict)),
                ('padrao', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Personalizado',
                'verbose_name_plural': 'Dashboards Personalizados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('navegacao', 'Navegação'), ('vendas', 'Vendas'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('usuario', 'Usuário'), ('sistema', 'Sistema'), ('erro', 'Erro')], max_length=20)),
                ('acao', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('propriedades', models.JSONField(default=dict)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Analytics',
                'verbose_name_plural': 'Eventos Analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada', models.BooleanField(default=False)),
                ('lida', models.BooleanField(default=False)),
                ('via_email', models.BooleanField(default=True)),
                ('via_sistema', models.BooleanField(default=True)),
                ('via_whatsapp', models.BooleanField(default=False)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoriaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('app_origem', models.CharField(help_text='Slug da app (ex: vendas, estoque)', max_length=50)),
                ('operacao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Alteração'), ('DELETE', 'Exclusão'), ('SECURITY', 'Segurança/Permissão')], max_length=10)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_posteriores', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria Operacional',
                'verbose_name_plural': 'Registros de Auditoria Operacional',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertaInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('vendas_baixas', 'Vendas Baixas'), ('erro_sistema', 'Erro do Sistema'), ('performance', 'Performance'), ('seguranca', 'Segurança'), ('financeiro', 'Financeiro')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='ativo', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('dados_contexto', models.JSONField(default=dict)),
                ('acoes_sugeridas', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Alerta Inteligente',
                'verbose_name_plural': 'Alertas Inteligentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
