# Generated by Django 6.0.2 on 2026-02-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainvestimento',
            name='fabricantes_vinculados',
            field=models.ManyToManyField(blank=True, to='produtos.fabricante', verbose_name='Fabricantes Financiados'),
        ),
        migrations.AddField(
            model_name='auditoriainvestimento',
            name='lotes_vinculados',
            field=models.ManyToManyField(blank=True, to='produtos.lote', verbose_name='Lotes Financiados'),
        ),
        migrations.AddField(
            model_name='auditoriainvestimento',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardpersonalizado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='dashboardpersonalizado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoanalytics',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_analytics', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='eventoanalytics',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacaoalerta',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.alertainteligente'),
        ),
        migrations.AddField(
            model_name='notificacaoalerta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertainteligente',
            name='usuarios_notificados',
            field=models.ManyToManyField(related_name='alertas_recebidos', through='analytics.NotificacaoAlerta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroauditoriaoperacional',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='registroauditoriaoperacional',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='registroauditoriaoperacional',
            name='fabricante_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.fabricante'),
        ),
        migrations.AddField(
            model_name='registroauditoriaoperacional',
            name='lote_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.lote'),
        ),
        migrations.AddField(
            model_name='registroauditoriaoperacional',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificacaoalerta',
            unique_together={('alerta', 'usuario')},
        ),
    ]
