# Generated by Django 6.0.2 on 2026-02-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaalteracao',
            options={'managed': False, 'ordering': ['-timestamp'], 'verbose_name': 'Auditoria', 'verbose_name_plural': 'Auditorias'},
        ),
    ]
