# Generated by Django 6.0.2 on 2026-02-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_auditoriaalteracao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertainteligente',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Alerta Inteligente', 'verbose_name_plural': 'Alertas Inteligentes'},
        ),
        migrations.AlterModelOptions(
            name='auditoriainvestimento',
            options={'managed': False, 'verbose_name': 'Vínculo de Auditoria de Investimento', 'verbose_name_plural': 'Vínculos de Auditoria de Investimento'},
        ),
        migrations.AlterModelOptions(
            name='dashboardpersonalizado',
            options={'managed': False, 'ordering': ['nome'], 'verbose_name': 'Dashboard Personalizado', 'verbose_name_plural': 'Dashboards Personalizados'},
        ),
        migrations.AlterModelOptions(
            name='eventoanalytics',
            options={'managed': False, 'ordering': ['-timestamp'], 'verbose_name': 'Evento Analytics', 'verbose_name_plural': 'Eventos Analytics'},
        ),
        migrations.AlterModelOptions(
            name='notificacaoalerta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registroauditoriaoperacional',
            options={'managed': False, 'ordering': ['-timestamp'], 'verbose_name': 'Registro de Auditoria Operacional', 'verbose_name_plural': 'Registros de Auditoria Operacional'},
        ),
        migrations.AlterModelTable(
            name='auditoriaalteracao',
            table='analytics_auditoriaalteracao',
        ),
    ]
