# Generated by Django 6.0.2 on 2026-02-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_alertainteligente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alertainteligente',
            table='analytics_alertainteligente',
        ),
        migrations.AlterModelTable(
            name='auditoriainvestimento',
            table='analytics_auditoriainvestimento',
        ),
        migrations.AlterModelTable(
            name='dashboardpersonalizado',
            table='analytics_dashboardpersonalizado',
        ),
        migrations.AlterModelTable(
            name='eventoanalytics',
            table='analytics_eventoanalytics',
        ),
        migrations.AlterModelTable(
            name='notificacaoalerta',
            table='analytics_notificacaoalerta',
        ),
        migrations.AlterModelTable(
            name='registroauditoriaoperacional',
            table='analytics_registroauditoriaoperacional',
        ),
    ]
